# ml/train_model.py
# AI Surrogate Model Training Pipeline
#
# A surrogate model is a fast approximation of an expensive calculation.
# Instead of running the full physics equations every time, the neural network
# learns to predict the answer directly from the input parameters.
#
# This is the same concept NASA uses in their trajectory optimization tools
# (e.g., GMAT's machine learning extensions) and ESA's Advanced Concepts Team.
#
# Run this script directly to retrain the model:
#   python ml/train_model.py

import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.metrics import mean_absolute_error, r2_score, mean_squared_error
import joblib


def train_surrogate_model():
    print("=" * 60)
    print("  ORBITAL MECHANICS — AI SURROGATE MODEL TRAINING")
    print("=" * 60)

    # ── 1. Load the synthetic dataset ─────────────────────────────────────────
    # The dataset was generated by generate_data.py using exact physics engines.
    # Every row is a 'ground truth' mission scenario with a known correct answer.
    current_folder = os.path.dirname(__file__)
    csv_path = os.path.join(current_folder, 'orbital_data.csv')

    print(f"\n[1/5] Loading dataset from: {csv_path}")
    df = pd.read_csv(csv_path)
    df = df.dropna()   # Remove any rows with missing values (data quality step)
    print(f"      Loaded {len(df):,} complete mission scenarios.")
    print(f"      Maneuver types: {df['Maneuver_Type'].value_counts().to_dict()}")

    # ── 2. Feature Engineering ────────────────────────────────────────────────
    # One-hot encode the maneuver type — neural networks can't work with text,
    # so "Hohmann" becomes [1, 0, 0], "Bi-Elliptic" becomes [0, 1, 0], etc.
    print("\n[2/5] Preparing features and targets...")
    df = pd.get_dummies(df, columns=['Maneuver_Type'])

    # Target: what we want the model to predict (propellant required in kg)
    y = df['Propellant_kg']

    # Features: everything the model can use as inputs
    # We drop the target AND Delta_V (that's a physics result, not an input)
    X = df.drop(columns=['Propellant_kg', 'Delta_V_ms'])

    print(f"      Feature columns: {X.columns.tolist()}")
    print(f"      Propellant range: {y.min():.1f} kg — {y.max():.1f} kg")

    # ── 3. Train / Test Split ─────────────────────────────────────────────────
    # We hold out 20% of the data to test on scenarios the model has never seen.
    # random_state=42 ensures reproducibility (same split every run).
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.20, random_state=42
    )
    print(f"\n[3/5] Split: {len(X_train):,} training / {len(X_test):,} test samples.")

    # ── 4. Build the Neural Network Pipeline ──────────────────────────────────
    print("\n[4/5] Training Neural Network (this may take a few minutes)...")

    # The StandardScaler normalises inputs to zero mean and unit variance.
    # Neural networks learn much better when all features are on the same scale.
    # Without scaling, a feature like Payload_kg (100–100,000) would dominate
    # over Phase_Angle (0–180) just because of its numerical magnitude.

    base_pipeline = Pipeline([
        ('scaler', StandardScaler()),
        ('nn', MLPRegressor(
            # Architecture: 3 hidden layers with 256 → 128 → 64 neurons.
            # Each layer learns increasingly abstract representations of the
            # orbital relationships. More neurons = more expressive, but also
            # more prone to overfitting. This size is well-calibrated for the
            # 100k sample dataset.
            hidden_layer_sizes=(256, 128, 64),

            # ReLU activation: max(0, x) — simple, efficient, avoids vanishing
            # gradient problems that sigmoid/tanh suffer from in deep networks.
            activation='relu',

            # Adam optimiser: adaptive learning rate, the industry standard for
            # training deep neural networks (used in most research papers).
            solver='adam',
            learning_rate_init=0.001,

            # Early stopping watches a validation subset during training and
            # stops when the model stops improving — prevents overfitting.
            # This is like having a test during training, not just at the end.
            early_stopping=True,
            validation_fraction=0.15,   # Hold back 15% of training data to monitor
            n_iter_no_change=25,         # Stop if no improvement for 25 epochs

            max_iter=2000,   # Safety cap on training epochs
            random_state=42
        ))
    ])

    # ── The Log Transform ("Solving the Whale Problem") ──────────────────────
    # Propellant mass follows the rocket equation's exponential: m = m_f × e^(Δv/IspG0)
    # This means small missions use 10 kg of fuel but interplanetary ones use 10,000 kg.
    # A neural network trying to minimise mean squared error will focus heavily on the
    # huge values and completely ignore the small ones.
    #
    # Solution: train on log(propellant) instead of propellant directly.
    # log1p(10) = 2.4   log1p(10000) = 9.2   — now they're close in scale!
    # expm1() is the exact inverse of log1p(), so predictions are auto-converted back.
    model = TransformedTargetRegressor(
        regressor=base_pipeline,
        func=np.log1p,       # Applied to y before training
        inverse_func=np.expm1  # Applied to y_pred before returning to caller
    )

    model.fit(X_train, y_train)
    print("      Training complete.")

    # ── 5. Evaluate Performance ───────────────────────────────────────────────
    print("\n[5/5] Evaluating on held-out test set...")
    predictions = model.predict(X_test)

    mae   = mean_absolute_error(y_test, predictions)
    rmse  = math.sqrt(mean_squared_error(y_test, predictions))
    r2    = r2_score(y_test, predictions)

    # MAPE: Mean Absolute Percentage Error — how wrong are we, on average, in %?
    # We clip the denominator to avoid division by zero for near-zero propellant masses.
    mape = np.mean(np.abs((y_test - predictions) / np.clip(y_test, 1, None))) * 100

    print("\n" + "─" * 45)
    print("  MODEL PERFORMANCE — TEST SET")
    print("─" * 45)
    print(f"  Mean Absolute Error (MAE) : {mae:>12,.2f} kg")
    print(f"  Root Mean Sq. Error (RMSE): {rmse:>12,.2f} kg")
    print(f"  Mean Abs. % Error (MAPE)  : {mape:>11.2f} %")
    print(f"  Accuracy Score (R²)       : {r2:>12.4f}  (1.0 = perfect)")
    print("─" * 45)

    if r2 > 0.99:
        print("  ✓ Excellent fit — ready for production use.")
    elif r2 > 0.95:
        print("  ✓ Good fit — suitable for mission planning estimates.")
    else:
        print("  ⚠ Moderate fit — consider generating more training data.")

    # ── Save the Trained Pipeline ─────────────────────────────────────────────
    # We save the entire pipeline (scaler + network + transformer) as one object.
    # This means the UI just calls model.predict(X) with raw inputs — no manual
    # scaling needed. The pipeline handles everything internally.
    model_path   = os.path.join(current_folder, 'surrogate_model.pkl')
    columns_path = os.path.join(current_folder, 'model_columns.pkl')

    joblib.dump(model, model_path)
    joblib.dump(X.columns.tolist(), columns_path)

    print(f"\n  Surrogate model saved → {model_path}")
    print(f"  Feature columns saved → {columns_path}")
    print("\n" + "=" * 60)
    print("  Training complete. Restart the dashboard to load the new model.")
    print("=" * 60)


if __name__ == "__main__":
    import math
    train_surrogate_model()